
server:
  port: 6969
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///mybatis-plus?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath:cn/itsource/mybatisplusdemo/mapper/*Mapper.xml
  type-aliases-package: cn.itsource.mybatisplusdemo.domain,cn.itsource.mybatisplusdemo.query

